"""Project settings for the local paper-only research system."""

PAPER_MODE = True
LIVE_TRADING_ALLOWED = False
DATA_DIR = "data"
LOG_DIR = "logs"
REPORT_DIR = "reports"
EXPORT_DIR = "exports"
DEFAULT_INITIAL_CAPITAL = 10000
DEFAULT_CONFIDENCE_THRESHOLD = 0.6
DEFAULT_MAX_DRAWDOWN = 0.2
DEFAULT_MAX_EXPOSURE = 0.3
DEFAULT_MAX_CONSECUTIVE_LOSSES = 3
DEFAULT_DAILY_LOSS_LIMIT = 0.02
DEFAULT_WEEKLY_LOSS_LIMIT = 0.05
